# Generated by Django 5.2.11 on 2026-03-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_cover_image_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('path', models.CharField(max_length=500)),
                ('referrer', models.URLField(blank=True, max_length=500, null=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('user_agent', models.TextField(blank=True)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('is_authenticated', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-visited_at'],
            },
        ),
    ]
